# Generated by Django 5.2 on 2025-04-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titulo de la tarea', max_length=50, verbose_name='Titulo')),
                ('is_completed', models.BooleanField(default=False, help_text='Si la tarea esta completa', verbose_name='¿Tarea completada?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(help_text='Descrición de la tarea', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['is_completed', 'created_at'],
            },
        ),
    ]
