# Generated by Django 5.2 on 2025-04-19 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_to',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha limite'),
            preserve_default=False,
        ),
    ]
